# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e083affdb644f414218697bad369f3ba865fbb156eb69c85c5fcca597aac54421a4ffce3e09d32a6df8f253c6361705f0eaac0fa4424fe7ae23f54d2022d1a30

test:
  secret_key_base: b6505ec96056030b62c9bb8d48b4ee271dd64c126794098bb7c04b5908e8f627b13672d27bc6bba0453a81dd5c4c53290cadd4caa47aa2b45736dd35bfebfb99

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
